Реализовано добавление и получение вакансий из базы
MironovaTatiana/repos pull request #1
Opened 2021-05-05 05:50 UTC by MironovaTatiana

2021-05-05 06:14 UTC, ilgizy commented on src/Application/Application.csproj
> +    <ProjectReference Include="..\..\Infrastructure\Infrastructure.csproj" />
почему код в Infrastructure лежит уровнем выше? Все должно быть в src

2021-05-05 06:16 UTC, ilgizy commented on src/Application/Dtos/JobDtoHelper.cs
> +    /// Класс для работы с JobDto
Называй вещи своими именами, более частными если возможно. Лучше Методы расширения нежели просто Класс

2021-05-05 06:20 UTC, ilgizy commented on src/Application/Services/VacanciesService.cs
> +            HttpClient httpClient = new ();
не совсем хороший вариант для использования new () . В данном случае var предпочтительнее

2021-05-05 06:23 UTC, ilgizy commented on src/Application/Services/VacanciesService.cs
> +                return new JobDto();
```suggestion
  // todo: проработать тему с исключениями. 
                return new JobDto();
```

2021-05-05 06:25 UTC, ilgizy commented on src/Application/UseCases/GetJob/IGetJobUseCase.cs
> +        ValueTask<IJob> ExecuteAsync(int id);
для чего ты используешь результат? в реализации и так используется OutputPort. Не кажется лишним?

2021-05-05 06:33 UTC, ilgizy commented on src/DataAccess/Repositories/JobsRepository.cs
> +            if ((int)_context.JobsList?.Count() > 0)
проверка на Null лишняя ( _context.JobsList? ), более того, если ты допускаешь  что может быть null то приведение к int завершится исключением, не так ли?

2021-05-05 06:34 UTC, ilgizy commented on src/DataAccess/Repositories/JobsRepository.cs
> +                if (job is Job findJob)
условие кажется избыточным

2021-05-05 06:35 UTC, ilgizy commented on src/DataAccess/Repositories/JobsRepository.cs
> +                var jobsFromDb = _context.JobsList.FromSqlRaw($"SELECT * FROM public.\"JobsList\" LIMIT @p0", n).ToList();
а тут почему решила использовать raw sql?

2021-05-05 06:36 UTC, ilgizy commented on src/DataAccess/Repositories/JobsRepository.cs
> +            int count = (int)(_context.JobsList?.Count());
не следует использовать приведение int? к int

2021-05-05 06:36 UTC, ilgizy commented on src/Domain/IJobsRepository.cs
> +        ValueTask<Job> GetJobById(int id);
тут и далее следует добавлять приставку Async

2021-05-05 06:38 UTC, ilgizy commented on src/WebApi/Modules/SQLExtensions.cs
>          public static IServiceCollection AddSQLServer(
нейминг не отражает то что делается в методе. К тому же под капотом  не SqlServer а Postgres

2021-05-05 06:40 UTC, ilgizy commented on Infrastructure/Config.cs
> +    public class Config
Следует делать частные и более специальные конфигурации. В данном случае этот класс назван слишком обобщенно, хотя он предназначен только для работы с hh.ru 
Лучше переименовать

2021-05-05 06:43 UTC, ilgizy commented on Infrastructure/Config.cs
> +        public string RequestVacanciesByCount => Requests.GetSection("RequestVacanciesByCount")?.Value;
не встречал такую технику, лучше сразу материализовать все свойства конфига при старте приложения.

2021-05-05 06:45 UTC, ilgizy commented on src/WebApi/Controllers/JobController.cs
> +            return await _useCase.ExecuteAsync(id)
а зачем ты уходишь от использования OutputPort
не понимаю мотива

2021-05-05 06:45 UTC, ilgizy commented on src/WebApi/Modules/SQLExtensions.cs
> +        /// Добавление SQL соединения
коммент не отражает то что делается в методе

2021-05-05 06:48 UTC, ilgizy commented on test/UnitTests/UseCases/GetJob/GetJobTests.cs
> +        [TestCase(2)]
тут параметризация теста выглядит лишней - что бы мы туда не передали, тест завершится одинаково.

2021-05-05 06:49 UTC, ilgizy commented on test/UnitTests/UseCases/GetJob/GetJobTests.cs
> +            Assert.AreEqual("Вакансия получена", expectedMessage);
можно еще добавить ассерт на результат.

2021-05-05 06:50 UTC, ilgizy commented on test/UnitTests/UseCases/GetJobsList/GetJobsListTests.cs
> +            mock.Setup(r => r.GetVacanciesList(count)).Returns(new ValueTask<IEnumerable<IJob>>(GetVacanciesDtoList()));
трудно читается, разнеси по разным строкам.

2021-05-05 07:01 UTC, ilgizy requested changes

2021-05-05 07:01 UTC, ilgizy commented on test/UnitTests/UseCases/GetJobsList/GetJobsListTests.cs
> +    /// Класс для тестирования получения списка вакансий
в тестах нет кейса когда проверяется требование с отключенным интернетом:
первый случай: мы проверяем, что при запросе данных из hh мы записали данные в БД
второй случай: мы проверяем, что при определенным случаях мы получили данные из БД (оффлайн, нет подключения к инету)

2021-05-05 07:01 UTC, ilgizy commented on test/UnitTests/UseCases/GetJobsList/GetJobsListTests.cs
> +        private static IEnumerable<Job> GetVacanciesList()
Лучше вынести в отд файл

2021-05-05 07:01 UTC, ilgizy commented on src/WebApi/Modules/SQLExtensions.cs
>      public static class SQLExtensions
Этот класс следует унести в ту сборку, сервисы которой он конфигурирует

2021-05-05 07:20 UTC, ilgizy commented on Infrastructure/Config.cs
> +        public string RequestVacanciesByCount => Requests.GetSection("RequestVacanciesByCount")?.Value;
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0

2021-05-05 07:22 UTC, ilgizy commented on src/Application/Services/VacanciesService.cs
> +        public Config Config { get; }
достачно приватного можификатора

2021-05-06 12:29 UTC, MironovaTatiana commented on src/WebApi/Modules/SQLExtensions.cs
>      public static class SQLExtensions
<IJobsRepository, JobsRepository> так в какую сборку перенести в  Domain или DataAccess

2021-05-10 15:42 UTC, MironovaTatiana commented on src/WebApi/Modules/SQLExtensions.cs
>      public static class SQLExtensions
<IJobsRepository, JobsRepository> так в какую сборку перенести в  Domain или DataAccess

2021-05-13 18:24 UTC, merged